### ISSUE TITLE
Error is always outdated

### ISSUE THREAD

**Issue by dh3wr** [DecentralizedAmateurPagingNetwork/Update-Check#2]
![grafik](https://user-images.githubusercontent.com/16710361/42027631-7b6fd93e-7aca-11e8-97a2-a4491056d5e8.png)

Nach dem hier ist die Realität neuer als die Referenz. Vielleicht kann man in diesem Fall das outdated gegen ein "Dein Stand ist sogar neuer als er sollte" ersetzen?

**Comment by menzerath** [comment]
Das Web-Frontend hat keine genaue Versionsprüfung drin, sondern prüft nur, ob der eigene Stand dem Stand aus diesem Repository entspricht oder nicht.

Da der Core nicht nach dem Konzept der [semantischen Versionierung](https://semver.org/) versioniert ist, wird hier eine paktegestützte Prüfung (zumindest im Web) auf "zu neu" / "zu alt" schwieriger.

**Comment by dh3wr** [comment]
Alles klar
